# Generated by Django 3.1.7 on 2021-09-16 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0010_auto_20210206_1726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название домашнего задания')),
                ('file', models.FileField(blank=True, upload_to='homeworks/', verbose_name='файл')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='account.groups_of_users')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_homeworks', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='homeworks.topic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='CompliteHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='complite_homeworks/', verbose_name='файл')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='статус задания')),
                ('task_comment', models.CharField(default='', max_length=500, verbose_name='комментарий к заданию')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complite_homework', to='homeworks.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выполненое домашнее задание',
                'verbose_name_plural': 'Выполненые Домашние задания',
            },
        ),
    ]
