# Generated by Django 3.2.8 on 2021-10-18 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210206_1726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='group',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='user',
        ),
        migrations.AddField(
            model_name='homework',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='homeworks', to='account.Groups_of_users'),
        ),
        migrations.AddField(
            model_name='homework',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='homeworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
