# Generated by Django 3.1.7 on 2021-09-16 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0010_auto_20210206_1726'),
        ('homeworks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRepeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='статус повторения')),
            ],
            options={
                'verbose_name': 'Повторение урока',
                'verbose_name_plural': 'Повторение уроков',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(blank=True, verbose_name='время начала')),
                ('time_end', models.TimeField(blank=True, verbose_name='время окончания')),
                ('status', models.IntegerField(default=0, verbose_name='статус урока')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.groups_of_users')),
                ('repeat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.lessonrepeat')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks.topic')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
