# Generated by Django 3.0.4 on 2020-03-21 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups_of_users',
            name='user',
        ),
        migrations.AddField(
            model_name='groups_of_users',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='group', to=settings.AUTH_USER_MODEL),
        ),
    ]
