# Generated by Django 3.0.4 on 2020-07-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200321_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups_of_users',
            old_name='group_name',
            new_name='name',
        ),
    ]
