# Generated by Django 3.0.4 on 2020-07-23 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200722_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups_of_users',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='название группы'),
        ),
        migrations.AlterField(
            model_name='groups_of_users',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата вступления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='последний вход'),
        ),
    ]
