# Generated by Django 3.0.4 on 2020-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200723_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=60, null=True, verbose_name='ФИО'),
        ),
    ]
