# Generated by Django 3.0.4 on 2020-07-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200723_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups_of_users',
            options={'verbose_name': 'Группы', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
