# Generated by Django 3.0.4 on 2020-09-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200723_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.SlugField(default='user', max_length=130, unique=True, verbose_name='ссылка на профиль'),
        ),
    ]
