# Generated by Django 3.0.4 on 2020-09-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.SlugField(max_length=130, unique=True, verbose_name='ссылка на профиль'),
        ),
    ]
