# Generated by Django 3.1.6 on 2021-02-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_is_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
